# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dmitrypugachev/hw/pmi-232-2-Dmitriy-Pugachev-sweezyk/tasks/image_processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dmitrypugachev/hw/pmi-232-2-Dmitriy-Pugachev-sweezyk/tasks/image_processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dmitrypugachev/hw/pmi-232-2-Dmitriy-Pugachev-sweezyk/tasks/image_processor/CMakeFiles /Users/dmitrypugachev/hw/pmi-232-2-Dmitriy-Pugachev-sweezyk/tasks/image_processor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dmitrypugachev/hw/pmi-232-2-Dmitriy-Pugachev-sweezyk/tasks/image_processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image_processor

# Build rule for target.
image_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_processor
.PHONY : image_processor

# fast build rule for target.
image_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/build
.PHONY : image_processor/fast

# target to build an object file
Color.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Color.o
.PHONY : Color.o

# target to preprocess a source file
Color.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Color.i
.PHONY : Color.i

# target to generate assembly for a file
Color.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Color.s
.PHONY : Color.s

# target to build an object file
FilterController.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/FilterController.o
.PHONY : FilterController.o

# target to preprocess a source file
FilterController.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/FilterController.i
.PHONY : FilterController.i

# target to generate assembly for a file
FilterController.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/FilterController.s
.PHONY : FilterController.s

# target to build an object file
FilterInterface.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/FilterInterface.o
.PHONY : FilterInterface.o

# target to preprocess a source file
FilterInterface.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/FilterInterface.i
.PHONY : FilterInterface.i

# target to generate assembly for a file
FilterInterface.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/FilterInterface.s
.PHONY : FilterInterface.s

# target to build an object file
Image.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Image.o
.PHONY : Image.o

# target to preprocess a source file
Image.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Image.i
.PHONY : Image.i

# target to generate assembly for a file
Image.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Image.s
.PHONY : Image.s

# target to build an object file
MatrixFilter.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/MatrixFilter.o
.PHONY : MatrixFilter.o

# target to preprocess a source file
MatrixFilter.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/MatrixFilter.i
.PHONY : MatrixFilter.i

# target to generate assembly for a file
MatrixFilter.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/MatrixFilter.s
.PHONY : MatrixFilter.s

# target to build an object file
PixelArray.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/PixelArray.o
.PHONY : PixelArray.o

# target to preprocess a source file
PixelArray.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/PixelArray.i
.PHONY : PixelArray.i

# target to generate assembly for a file
PixelArray.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/PixelArray.s
.PHONY : PixelArray.s

# target to build an object file
filters/Crop.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Crop.o
.PHONY : filters/Crop.o

# target to preprocess a source file
filters/Crop.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Crop.i
.PHONY : filters/Crop.i

# target to generate assembly for a file
filters/Crop.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Crop.s
.PHONY : filters/Crop.s

# target to build an object file
filters/Grayscale.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Grayscale.o
.PHONY : filters/Grayscale.o

# target to preprocess a source file
filters/Grayscale.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Grayscale.i
.PHONY : filters/Grayscale.i

# target to generate assembly for a file
filters/Grayscale.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Grayscale.s
.PHONY : filters/Grayscale.s

# target to build an object file
filters/Negative.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Negative.o
.PHONY : filters/Negative.o

# target to preprocess a source file
filters/Negative.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Negative.i
.PHONY : filters/Negative.i

# target to generate assembly for a file
filters/Negative.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Negative.s
.PHONY : filters/Negative.s

# target to build an object file
filters/Sharpening.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Sharpening.o
.PHONY : filters/Sharpening.o

# target to preprocess a source file
filters/Sharpening.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Sharpening.i
.PHONY : filters/Sharpening.i

# target to generate assembly for a file
filters/Sharpening.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Sharpening.s
.PHONY : filters/Sharpening.s

# target to build an object file
image_processor.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.o
.PHONY : image_processor.o

# target to preprocess a source file
image_processor.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.i
.PHONY : image_processor.i

# target to generate assembly for a file
image_processor.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.s
.PHONY : image_processor.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_processor"
	@echo "... Color.o"
	@echo "... Color.i"
	@echo "... Color.s"
	@echo "... FilterController.o"
	@echo "... FilterController.i"
	@echo "... FilterController.s"
	@echo "... FilterInterface.o"
	@echo "... FilterInterface.i"
	@echo "... FilterInterface.s"
	@echo "... Image.o"
	@echo "... Image.i"
	@echo "... Image.s"
	@echo "... MatrixFilter.o"
	@echo "... MatrixFilter.i"
	@echo "... MatrixFilter.s"
	@echo "... PixelArray.o"
	@echo "... PixelArray.i"
	@echo "... PixelArray.s"
	@echo "... filters/Crop.o"
	@echo "... filters/Crop.i"
	@echo "... filters/Crop.s"
	@echo "... filters/Grayscale.o"
	@echo "... filters/Grayscale.i"
	@echo "... filters/Grayscale.s"
	@echo "... filters/Negative.o"
	@echo "... filters/Negative.i"
	@echo "... filters/Negative.s"
	@echo "... filters/Sharpening.o"
	@echo "... filters/Sharpening.i"
	@echo "... filters/Sharpening.s"
	@echo "... image_processor.o"
	@echo "... image_processor.i"
	@echo "... image_processor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

